### ISSUE TITLE
Add update notification, when a new version is available

### ISSUE THREAD

**Issue by fayer3** [ferriarnus/VivecraftForge#147]
add a  notification, when a new version is available, either at startup, or in chat when joining a world

**Comment by hammy275** [comment]
For Forge, it may be worth adding a `updateJSONURL` in `mods.toml` to add a notification to the "Mods" button alongside any other notification options.

Since Vivecraft is already up on Modrinth, they provide [a service](https://docs.modrinth.com/docs/tutorials/forge_updates/) for this so you can just add the URL to the `mods.toml` and let them do the work of hosting and generating the JSON file.
